blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://calve.readthedocs.io
    about: Check the docs for setup guides, CLI reference, and tutorials.
  - name: 💬 Discussions
    url: https://github.com/geocoug/calve/discussions
    about: Ask questions and discuss ideas with the community.
